# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- release

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.2.0'
  displayName: 'Install Node.js'

- task: DownloadSecureFile@1
  inputs:
    secureFile: '.env'

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Agent.TempDirectory)
    Contents: '**\.env'
    TargetFolder: $(Build.SourcesDirectory)

- script: |
    npm install
    npm run test:all
    npm run build
    VERSION=$(Build.buildnumber) npm run build
    VERSION=$(Build.buildnumber) npm run sentry:upload:sourcemaps
  displayName: 'Run tests, build for release and upload sourcemaps to Sentry'

- task: CopyFiles@2
  inputs:
    Contents: 'public/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs: 
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'releaseBuild'

- script: |
    VERSION=$(Build.buildnumber) npm run sentry:release:finalize
  displayName: 'Finalize Sentry release'

    